extends Node2D

class_name Team;

signal fighter_died(fighter:ActiveFighter)


signal fighter_converted(fighter:ActiveFighter);
## team that LOSES the converted unit emits it


@export var roster:Roster;
@export var npc_fighter_scene:PackedScene

@export var arena:Arena

@export var team_n:int;
@export var enemy_team:Team;

@export var ground_elements:Node2D;
@export var projectiles:Node2D;

var leader_fighter:ActiveFighter
var leader:Leader;

var fighters:Array[ActiveFighter];



var col_count:int = 0;
func load_roster()->void:
	var cols := {"melee":[], "mid":[], "long":[]};
	for unit:FighterUnit in roster.units:

		var fighter:NpcFighter = generate_fighter(unit);
		
		match unit.base.skill_range:
			FighterBase.MELEE_RANGE:
				cols.melee.append(fighter);
			FighterBase.MID_RANGE:
				cols.mid.append(fighter);
			FighterBase.LONG_RANGE:
				cols.long.append(fighter);
			_:
				assert(false);

	position_column(cols.melee, 500, 200);
	position_column(cols.mid, 700, 200);
	position_column(cols.long, 1000, 200)


func generate_fighter(unit:FighterUnit, force_position:Vector2=Vector2.ZERO)->NpcFighter:
	var fighter:NpcFighter = npc_fighter_scene.instantiate();
	fighter.ally_team = self;
	fighter.load_fighter(unit);
	
	if force_position:
		## for summons
		fighter.position = force_position
		
	assign_entity(fighter)
	

	
	add_child.call_deferred(fighter)
	
	## so i can keep setting the fighter_base shader and then it just 
	## gets turned to unique resource here
	## and combat effects can affect the shaders individually
	fighter.sprite.material = fighter.sprite.material.duplicate();
	
	ColorCoder.color_code_fighter(fighter, team_n)

	
	return fighter

func position_column(col:Array, x_origin:int, y_origin:int)->void:
	const y_gap:int = 100;
	var col_gap:int = 50;
	const fighters_per_col = 5;
	
	if team_n == 1:
		x_origin *= -1
		col_gap *= -1;
		
	for i:int in len(col):
		var fighter:NpcFighter = col[i]
		fighter.position.x = x_origin + (col_count * col_gap);
		fighter.position.y = y_origin + (y_gap * ((i+1) % fighters_per_col))
		
		if i % fighters_per_col == 0:
			col_count += 1;
	
func assign_fighter(fighter:ActiveFighter)->void:
	if fighter.base.hit_scan:
		if fighter.base.skill.scan_enemies:
			fighter.base.hit_scan.set_collision_mask_value(enemy_team.team_n, true);
		if fighter.base.skill.scan_allies:
			fighter.base.hit_scan.set_collision_mask_value(team_n, true);
	if fighter.base.projectile:
		fighter.base.projectile.setup(fighter)

func assign_entity(target:CombatEntity)->void:
	fighters.append(target);
	## double declaration to catch the player and the autogenerated fighters
	target.ally_team = self
	target.enemy_team = enemy_team;
	target.death.connect(on_entity_death.bind(target))
	target.hurtbox.set_collision_layer_value(team_n, true);
	
	arena.battle_ended.connect(target.on_battle_over)
	if not target is PlayerFighter and not target.dummy:
		assign_fighter(target)
	
	


func unassign_fighter(fighter:ActiveFighter)->void:
	fighters.erase(fighter);
	fighter.death.disconnect(on_entity_death);
	
	fighter.set_collision_layer_value(team_n, false);
	if fighter.base.hit_scan:
		## will just hide it if converted from enemy team
		## to playe team
		if fighter.base.skill.scan_enemies:
			fighter.base.hit_scan.set_collision_mask_value(enemy_team.team_n, false);
		if fighter.base.skill.scan_allies:
			fighter.base.hit_scan.set_collision_mask_value(team_n, false);
			

func convert_fighter(fighter:ActiveFighter)->void:
	## STEALS THE UNIT FROM THE ENEMY TEAEM
	## right now only used on allegiance shifter
	## new unit design type sh?
	enemy_team.unassign_fighter(fighter)

	fighter.reparent(self);
	assign_entity(fighter)
	enemy_team.fighter_converted.emit(fighter)


func _on_child_entered_tree(node: Node) -> void:
	if node not in fighters:
		## leave this on like this so i can just test 
		## by throwing nodes into the editor
		## it where  also summoning units makes
		## you just need to add them to the team node and 
		## it works just like everyone else
		assert(node is CombatEntity or node is NpcFighterTest or node is Prop);
		if node is ActiveFighter:
			assign_entity(node)

func on_entity_death(_killer:ActiveFighter, fighter:CombatEntity)->void:
	## WHERE BATTLES ARE FINISHED RIGHT NOW
	## you lose when the player unit dies
	## you win when you wipe out enemy team
	
	fighters.erase(fighter)
	if len(fighters) == 0 and team_n == 2:
		arena.finish_battle(true)

	if fighter == Entities.player_fighter:
		arena.finish_battle(false);
	fighter_died.emit(fighter)
