extends Inventory;

class_name NpcInventory;
@export var fixed_items:Array[Item];
@export var item_pool:Array[Item]
## only affects non-player inventories, generated by the owner of the inventory,

const buying_price_multiplier = 1.5
@onready var resource_buying_prices:Dictionary[String, float] = {
	## RESOURCE BUYING PRICE = PLAYER BUYING
	"food":Index.resource_base_prices["food"]*buying_price_multiplier,
	"fuel":Index.resource_base_prices["fuel"]*buying_price_multiplier,
	"juice":Index.resource_base_prices["juice"]*buying_price_multiplier,
	"scrap":Index.resource_base_prices["scrap"]*buying_price_multiplier,
	"chips":Index.resource_base_prices["chips"]*buying_price_multiplier
}

const selling_prices_divider = 1.5
@onready var resource_selling_prices:Dictionary[String, float] = {
	## RESOURCE SELLING PRICE = PLAYER SELLING
	"food":Index.resource_base_prices["food"]/selling_prices_divider,
	"fuel":Index.resource_base_prices["fuel"]/selling_prices_divider,
	"juice":Index.resource_base_prices["juice"]/selling_prices_divider,
	"scrap":Index.resource_base_prices["scrap"]/selling_prices_divider,
	"chips":Index.resource_base_prices["chips"]/selling_prices_divider
}

func _on_child_entered_tree(node: Node) -> void:
	assert(node is Item);
	if node in item_pool:
		remove_child.call_deferred(node);
	else:
		super(node)

func refresh_inventory()->void:
	var to_erase:Array[Item]
	for item in items:
		## can't erase them in-loop
		if not item in fixed_items:
			to_erase.append(item)
			
	for item:Item in to_erase:
		remove_item(item);
		
	## will establish trade prices for all resources, farms (and other resource-trade based buildings)
	## will buy any resources the player gives them and sell them at the turn of the day
	## getting back the money they spent on them

	
	if money < 100:
		money = randi_range(75, 150);

	
	if holder is ResourceTrader:
		var tradeable_resources:PackedStringArray = Index.all_resources.filter(func(r:String)->bool:return r != "money")
		for r:String in tradeable_resources:
			if holder.to_trade[r]:
				var production:int = randi_range(250, 750);
				self[r] = production;
			else:
				if self[r]:
					money += self[r] * resource_selling_prices[r]
					self[r] = 0
	if holder is Trader:
		var item_amount:int = randi_range(holder.max_item/2, holder.max_items);
		for i:int in item_amount:
			## TODO implement the rarity rate
			var item:Item = item_pool.pick_random().duplicate();
			add_item(item);
	
	store_resources();
