extends Inventory;

class_name ShopInventory;
## implements trade menu generation and pricing

@export_range(1, 5) var rarity_rate:int=1;
@export var batch_size:int

@export var resource_storage:Array[ResourceContainer]
## right now only resource containers for daily stock
@export var item_pool:Array[Item]
## only affects non-player inventories, generated by the owner of the inventory,
var pool_generated:bool=false;

const buying_prices_multiplier = 1.5
@onready var resource_buying_prices:Dictionary[String, float] = {
	## RESOURCE BUYING PRICE = PLAYER BUYING
	"food":Index.resource_base_prices["food"]*buying_prices_multiplier,
	"fuel":Index.resource_base_prices["fuel"]*buying_prices_multiplier,
	"juice":Index.resource_base_prices["juice"]*buying_prices_multiplier,
	"scrap":Index.resource_base_prices["scrap"]*buying_prices_multiplier,
	"chips":Index.resource_base_prices["chips"]*buying_prices_multiplier
}

const selling_prices_divider = 1.5
@onready var resource_selling_prices:Dictionary[String, float] = {
	## RESOURCE SELLING PRICE = PLAYER SELLING
	"food":Index.resource_base_prices["food"]/selling_prices_divider,
	"fuel":Index.resource_base_prices["fuel"]/selling_prices_divider,
	"juice":Index.resource_base_prices["juice"]/selling_prices_divider,
	"scrap":Index.resource_base_prices["scrap"]/selling_prices_divider,
	"chips":Index.resource_base_prices["chips"]/selling_prices_divider
}

func _ready()->void:
	super();
	pool_generated = true;

func _on_child_entered_tree(node: Node) -> void:
	assert(node is Item);
	if not pool_generated:
		if not node is ResourceContainer or not node in resource_storage:
			item_pool.append(node);
		else:
			add_item(node);
		## pool items can be removed as they're only ever used for duplicating
		## to the same index pointer bullshit as i did for fighterbases?
	else:
		super(node)

func refresh_inventory()->void:
	var to_erase:Array[Item]
	for item in items:
		## can't erase them in-loop
		if not item in resource_storage:
			to_erase.append(item)
			
	for item:Item in to_erase:
		remove_item(item);
		
	for c:ResourceContainer in resource_storage:
		c.stack_size = randi_range(c.capacity/1.75, c.capacity)
	
	money = randi_range(750, 1000)
	## figure this out some other time for now everyone can just sell away

	var rarity_1_items:Array[Item] = item_pool.filter(func(item:Item)->bool:return item.rarity == 1)
	var rarity_2_items:Array[Item] = item_pool.filter(func(item:Item)->bool:return item.rarity == 2)
	var rarity_3_items:Array[Item] = item_pool.filter(func(item:Item)->bool:return item.rarity == 3)

	assert(len(rarity_1_items) and len(rarity_2_items) and len(rarity_3_items))
	var roll_rates:Array[float] = get_roll_rates()
	
	var amount:int = randi_range(max(1, batch_size - 2), batch_size + 2)
	

	for i:int in amount:
		var roll:float = randf_range(0, 1);
		var rarity:int = 1;
		if roll > roll_rates[0]:
			if roll > roll_rates[0] + roll_rates[1]:
				rarity = 3;
			else:
				rarity = 2
		var new_item:Item
		match rarity:
			1:
				new_item = rarity_1_items.pick_random().duplicate();
			2:
				new_item = rarity_2_items.pick_random().duplicate()
			3:
				new_item = rarity_3_items.pick_random().duplicate()
		add_child(new_item);
	
	refresh_resource_counts();
	

func get_roll_rates()->Array[float]:
	match rarity_rate:
		1:
			return [.85, .1, .05];
		2:
			return [.7, .2, .1];
		3:
			return [.6, .25, .15];
		4:
			return [.5, .3, .2];
		5:
			return [.3, .4, .3];
	assert(false)
	return []
