extends Node2D

## any settlement or party has an inventory
class_name Inventory;

@export var non_sellable_items:Array[Item];

@export var holder:Node;

@export_subgroup("Resources")
@export var food:int;
@export var money:float;
@export var fuel:int;

@export var juice:int;
@export var scrap:int;
@export var chips:int;

@export_subgroup("Items")
@export var containers:Array[ResourceContainer];
@export var consumables:Array[Consumable];
@export var trinkets:Array[Trinket];

@export_subgroup("Equipment")
@export var weapons:Array[Weapon];
@export var modules:Array[Module];

var capacity_x:int = 8;
var capacity_y:int = 12;

func _ready()->void:
	refresh_resource_counts();
	
func refresh_resource_counts(_resource:String="", _amount:int=0)->void:
	for r:String in Index.all_resources:
		if r != "money":
			self[r] = 0;
	for c in containers:
		self[c.resource] += c.stack_size;

func _on_child_entered_tree(node: Node) -> void:
	## INVENTORIES AND ROSTERS JUST NEED TO HAVE THE UNITS AS CHILDREN TO PROPERLY CATEGORIZE THEM
	assert(node is Item)
	if node is Consumable:
		consumables.push_back(node);
	elif node is Trinket:
		trinkets.push_back(node);
	elif node is Module:
		modules.push_back(node);
	elif node is Weapon:
		weapons.push_back(node);
	elif node is ResourceContainer and not (node in containers):
		## default containers from travelling traders will be manually added to the containers array 
		## so the resources can be restored before entering the tree
		containers.append(node)


func change_resource(resource:String, amount:int)->void:
	## only runs if the inventory has enough resources to remove
	assert(self[resource] >= amount * -1)
	if resource != 'money':
		var containers_with_resource:Array[ResourceContainer];
		for c:ResourceContainer in containers:
			if c.resource == resource:
				containers_with_resource.append(c)
				
		containers_with_resource.sort_custom(containers[0].capacity_sort);
		
		var i:int = 0;
		if amount < 0:
			var to_remove:int = -amount
			while to_remove:
				var c:ResourceContainer = containers_with_resource[i];
				if c.stack_size >= to_remove:
					c.stack_size -= to_remove;
					to_remove = 0;
					c.check_empty();
				else:
					to_remove -= c.stack_size;
					c.stack_size = 0;
					c.check_empty()
				i += 1;
		else:
			var to_add:int = amount;
			while to_add:
				if i < len(containers_with_resource):
					var c:ResourceContainer = containers_with_resource[i];
					if c.space_left() >= to_add:
						c.stack_size += to_add;
						to_add = 0;
					else:
						to_add -= c.space_left()
						c.stack_size += c.space_left();
				else:
					var raw_stack:ResourceContainer = Index[resource + "_stack_scene"].instantiate();
					if "mirror_only" in raw_stack:
						## somehow signal that resources went to waste?
						to_add = 0;
					else:
						if raw_stack.capacity >= to_add:
							raw_stack.stack_size = to_add;
							to_add = 0;
						else:
							## sometimes there won't be enough room?
							raw_stack.stack_size = raw_stack.capacty;
							to_add -= raw_stack.capacity;
							add_child(raw_stack)
				i += 1
	else:
		money += amount
	if holder is Player:
		Entities.player.resource_changed.emit(resource, amount);

## only affects non-player inventories, generated by the owner of the inventory,
## prices here are the final price per-unit that will be available in the trade
@onready var resource_buying_prices:Dictionary[String, float] = {
	## RESOURCE BUYING PRICE = PLAYER BUYING
	"food":Index.resource_base_prices["food"]*2,
	"fuel":Index.resource_base_prices["fuel"]*2,
	"juice":Index.resource_base_prices["juice"]*2,
	"scrap":Index.resource_base_prices["scrap"]*2,
	"chips":Index.resource_base_prices["chips"]*2
}

@onready var resource_selling_prices:Dictionary[String, float] = {
	## RESOURCE SELLING PRICE = PLAYER SELLING
	"food":Index.resource_base_prices["food"]/2,
	"fuel":Index.resource_base_prices["fuel"]/2,
	"juice":Index.resource_base_prices["juice"]/2,
	"scrap":Index.resource_base_prices["scrap"]/2,
	"chips":Index.resource_base_prices["chips"]/2
}



func _on_child_exiting_tree(node: Node) -> void:
	assert(node is Item)
	if node is Consumable:
		consumables.erase(node);
	elif node is Trinket:
		trinkets.erase(node);
	elif node is Module:
		modules.erase(node);
	elif node is Weapon:
		weapons.erase(node);
	elif node is ResourceContainer:
		containers.erase(node)
		
func store_resources()->void:
	## used after resources are gained from whatever source, allocates 
	## unallocated resources to the containers with the highest capacity
	for r:String in Index.all_resources:
		if r != "money":
			var total:int = self[r];
			var already_stored:int = 0;
			var containers_with_space:Array[ResourceContainer] 
			
			for container:ResourceContainer in containers:
				if container.resource == r:
					already_stored += container.stack_size;
					if container.space_left():
						if holder == Entities.player:
							containers_with_space.append(container);
						else:
							if container in non_sellable_items:
								## sellable containers will always be empty
								containers_with_space.append(container);
			if len(containers_with_space):
				containers_with_space.sort_custom(containers[0].capacity_sort)

			## will always be at least 0, as this function will be 
			## ran mostly after resources have been gained
			var to_store:int = total - already_stored;
			for c:ResourceContainer in containers_with_space:
				if c.space_left() >= to_store:
					c.stack_size += to_store;
					to_store = 0;
				else:
					var to_add:int = c.space_left();
					c.stack_size += to_add;
					to_store -= to_add;
			
			if to_store and holder == Entities.player:
				## only player inventory gets to have raw stack everyone else's stuff just goes to waste
				## (only upon generation/trading rn)
				var raw_stack:ResourceContainer = Index[r + "_stack_scene"].instantiate();
				if not "mirror_only" in raw_stack:
					while to_store:
						var stack:ResourceContainer = raw_stack.duplicate();
						if stack.capacity < to_store:
							stack.stack_size = stack.capacity;
							add_child(stack)
							to_store -= stack.capacity
						else:
							add_child(stack);
							stack.stack_size = to_store
							to_store = 0;
				else:
					## if stack is liquid and there's no room for it, it goes to waste
					## settlements refuse trades for stuff they can't store?
					self[r] -= to_store;


func sort_items()->void:
	## only ever run if guaranteed that everything will fit
	var all_items:Array[Item] = []
	for item in get_children():
		item.inventory_position = Vector2(-1, -1)
		all_items.append(item)
	all_items.sort_custom(size_sort);
	
	## merely projects a grid instead of creating the who display
	var taken_cells:Array[Vector2];
	for item in all_items:
		if item != Entities.player.equipped_module and\
		item != Entities.player.equipped_weapon and\
		item != Entities.player.alternative_weapon:
			throw_item(item, taken_cells);

func size_sort(a:Item, b:Item)->bool:
	return a.size_x * a.size_y > b.size_x * b.size_y;

func throw_item(item:Item, taken_cells:Array[Vector2])->void:
	## every non-player inventory is top-right oriented instead of top-left
	var spot:Vector2;
	if self == Entities.player.inventory:
		spot = Vector2.ZERO;
	else:
		spot = Vector2(capacity_x - 1, 0);
	while not fits_in_spot(item, spot, taken_cells):
		if self == Entities.player.inventory:
			spot.x += 1;
			if spot.x == capacity_x:
				spot.x = 0;
				spot.y  += 1;
		else:
			spot.x -= 1;
			if spot.x == - 1:
				spot.x = capacity_x - 1;
				spot.y += 1;
	item.inventory_position = spot;
	for x:int in item.size_x:
		for y:int in item.size_y:
			taken_cells.append(Vector2(x + spot.x, y + spot.y))
	
	
func fits_in_spot(item:Item, spot:Vector2, taken_cells:Array[Vector2])->bool:
	for x:int in item.size_x:
		for y:int in item.size_y:
			var to_check:Vector2 = Vector2(x + spot.x, y + spot.y);
			if not cell_in_grid(to_check) or to_check in taken_cells:
				return false;
	return true

func cell_in_grid(cell:Vector2)->bool:
	if cell.x < 0 or cell.x >= capacity_x:
		return false;
	if cell.y < 0 or cell.y >= capacity_y:
		return false;
	return true;
