extends Node2D

## any settlement or party has an inventory
class_name Inventory;

@export var non_sellable_items:Array[Item];

@export var holder:Node;

@export_subgroup("Resource Counters")
## resource counters and resource items remain consistant with eachother
## and can both be used for checking and updating eachother
@export var food:int;
@export var money:int;
@export var fuel:int;

@export var juice:int;
@export var scrap:int;
@export var chips:int;

@export_subgroup("Items")
@export var items:Array[Item];

@export var containers:Array[ResourceContainer];
@export var consumables:Array[Consumable];
@export var trinkets:Array[Trinket];

@export_subgroup("Equipment")
@export var weapons:Array[Weapon];
@export var modules:Array[Module];

@export var capacity_x:int = 8;
@export var capacity_y:int = 12;

func _ready()->void:
	refresh_resource_counts();
	
func refresh_resource_counts(_resource:String="", _amount:int=0, emit_change:bool=false)->void:
	var previous_amounts: = {}
	for r:String in Index.all_resources:
		previous_amounts[r] = self[r];
		if r != "money":
			self[r] = 0;
	for c in containers:
		self[c.resource] += c.stack_size;
	
	if emit_change:
		for r:String in Index.all_resources:
			if previous_amounts[r] != self[r]:
				## will not make an infinite loop, but will make this 
				## retrigger itself a few unnecessary times?
				Entities.player.resource_changed.emit(r, self[r] - previous_amounts[r]);

	



func change_resource(resource:String, amount:int)->void:
	## only runs if the inventory has enough resources to remove
	assert(self[resource] >= amount * -1)
	if resource != 'money':
		var containers_with_resource:Array[ResourceContainer];
		for c:ResourceContainer in containers:
			if c.resource == resource:
				containers_with_resource.append(c)
				
		containers_with_resource.sort_custom(containers[0].capacity_sort);
		
		var i:int = 0;
		if amount < 0:
			var to_remove:int = -amount
			while to_remove:
				var c:ResourceContainer = containers_with_resource[i];
				if c.stack_size >= to_remove:
					c.stack_size -= to_remove;
					to_remove = 0;
					c.check_empty();
				else:
					to_remove -= c.stack_size;
					c.stack_size = 0;
					c.check_empty()
				i += 1;
		else:
			var to_add:int = amount;
			while to_add:
				if i < len(containers_with_resource):
					var c:ResourceContainer = containers_with_resource[i];
					if c.space_left() >= to_add:
						c.stack_size += to_add;
						to_add = 0;
					else:
						to_add -= c.space_left()
						c.stack_size += c.space_left();
				else:
					var raw_stack:ResourceContainer = Index[resource + "_stack_scene"].instantiate();
					if "mirror_only" in raw_stack:
						## somehow signal that resources went to waste?
						to_add = 0;
					else:
						if raw_stack.capacity >= to_add:
							raw_stack.stack_size = to_add;
							to_add = 0;
						else:
							## sometimes there won't be enough room?
							raw_stack.stack_size = raw_stack.capacty;
							to_add -= raw_stack.capacity;
							add_item(raw_stack)
				i += 1
	else:
		money += amount
	if holder is Player:
		Entities.player.resource_changed.emit(resource, amount);

## only affects non-player inventories, generated by the owner of the inventory,
## prices here are the final price per-unit that will be available in the trade
@onready var resource_buying_prices:Dictionary[String, float] = {
	## RESOURCE BUYING PRICE = PLAYER BUYING
	"food":Index.resource_base_prices["food"]*2,
	"fuel":Index.resource_base_prices["fuel"]*2,
	"juice":Index.resource_base_prices["juice"]*2,
	"scrap":Index.resource_base_prices["scrap"]*2,
	"chips":Index.resource_base_prices["chips"]*2
}

@onready var resource_selling_prices:Dictionary[String, float] = {
	## RESOURCE SELLING PRICE = PLAYER SELLING
	"food":Index.resource_base_prices["food"]/2,
	"fuel":Index.resource_base_prices["fuel"]/2,
	"juice":Index.resource_base_prices["juice"]/2,
	"scrap":Index.resource_base_prices["scrap"]/2,
	"chips":Index.resource_base_prices["chips"]/2
}

func add_item(item: Item, generated:bool=false) -> void:
	assert(not item in items)
	## INVENTORIES AND ROSTERS JUST NEED TO HAVE THE UNITS AS CHILDREN TO PROPERLY CATEGORIZE THEM
	if not item.is_inside_tree():
		add_child(item);
	else:
		item.reparent(self);
		
	items.append(item);
	if item is Consumable:
		consumables.append(item);
	elif item is Trinket:
		trinkets.append(item);
	elif item is Module:
		modules.append(item);
	elif item is Weapon:
		weapons.append(item);
	elif item is ResourceContainer:
		## default containers from travelling traders will be manually added to the containers array 
		## so the resources can be restored before entering the tree
		containers.append(item)

		

func remove_item(item:Item)->void:
	assert(item in items);

	items.erase(item);
	if item is Consumable:
		consumables.erase(item);
	elif item is Trinket:
		trinkets.erase(item);
	elif item is Module:
		modules.erase(item);
	elif item is Weapon:
		weapons.erase(item);
	elif item is ResourceContainer:
		containers.erase(item)




func clear_containers()->void:
	## CANT ITERATE OVER AN ARRAY WHILE MOVING/DELETINGS ITS ELEMENTS XDD
	var to_remove:Array[ResourceContainer]
	for c:ResourceContainer in containers:
		if "raw_stack" in c:
			## cam't just queue fere because it needs to be 
			## out of the items array in the same frame
			to_remove.append(c)
		else:
			c.stack_size = 0;
			
	for c:ResourceContainer in to_remove:
		## CANT ITERATE OVER AN ARRAY WHILE MOVING/DELETINGS ITS ELEMENTS XDD
		remove_item(c);

func store_resources()->void:
	
	## used after resources are gained from whatever source, allocates 
	## unallocated resources to the containers with the highest capacity
	clear_containers();
	
	for r:String in Index.all_resources:
		if r != "money":
			var to_store:int = self[r];
			if holder is Settlement or holder is NpcLeader:
				var storage:ResourceContainer = holder[r+"_storage"];
				storage.stack_size += to_store;
			else:
				var containers_with_resource:Array[ResourceContainer]=\
				containers.filter(func(a:ResourceContainer)->bool:return a.resource == r);
				containers_with_resource.sort_custom(sort_containers);
				for c:ResourceContainer in containers_with_resource:
					c.stack_size = 0;
					if to_store:
						if c.capacity >= to_store:
							c.stack_size = to_store;
							to_store = 0;
							
						else:
							c.stack_size = c.capacity;
							to_store -= c.capacity;
				while to_store:
					var raw_stack:ResourceContainer = Index[r+"_stack_scene"].instantiate()
					if "mirror_only" in raw_stack or raw_stack.capacity >= to_store:
						raw_stack.stack_size = to_store;
						to_store = 0;
					else:
						raw_stack.stack_size = raw_stack.capacity;
						to_store -= raw_stack.capacity;
					add_item(raw_stack);
					
					

					
func sort_items()->void:
	## only ever run if guaranteed that everything will fit
	store_resources()
		
	for item in items:
		item.inventory_position = Vector2(-1, -1)
	
	## merely projects a grid instead of creating the who display
	var taken_cells:Array[Vector2];
	for item in items:
		if item != Entities.player.equipped_module and\
		item != Entities.player.equipped_weapon and\
		item != Entities.player.alternative_weapon:
			throw_item(item, taken_cells);


func size_sort(a:Item, b:Item)->bool:
	return a.size_x * a.size_y > b.size_x * b.size_y;

func throw_item(item:Item, taken_cells:Array[Vector2])->void:
	## every non-player inventory is top-right oriented instead of top-left
	## ONLY ITEMS THAT FIT CAN MAKE IT HERE
	var spot:Vector2;
	if self == Entities.player.inventory:
		spot = Vector2.ZERO;
	else:
		spot = Vector2(capacity_x - 1, 0);
	while not fits_in_spot(item, spot, taken_cells):
		if self == Entities.player.inventory:
			spot.x += 1;
			if spot.x == capacity_x:
				spot.x = 0;
				spot.y  += 1;
		else:
			spot.x -= 1;
			if spot.x == - 1:
				spot.x = capacity_x - 1;
				spot.y += 1;

	item.inventory_position = spot;
	for x:int in item.size_x:
		for y:int in item.size_y:
			taken_cells.append(Vector2(x + spot.x, y + spot.y))
	
	
func fits_in_spot(item:Item, spot:Vector2, taken_cells:Array[Vector2])->bool:
	for x:int in item.size_x:
		for y:int in item.size_y:
			var to_check:Vector2 = Vector2(x + spot.x, y + spot.y);
			if not cell_in_grid(to_check) or to_check in taken_cells:
				return false;
	return true

func cell_in_grid(cell:Vector2)->bool:
	if cell.x < 0 or cell.x >= capacity_x:
		return false;
	if cell.y < 0 or cell.y >= capacity_y:
		return false;
	return true;


func _on_child_entered_tree(node: Node) -> void:
	assert(node is Item);
	if not node in items:
		## ONLY EVER FROM INVENTORIES THAT WERE MADE IN-EDITOR
		add_item(node);

func sort_containers(a:ResourceContainer, b:ResourceContainer)->bool:
	if a.capacity > b.capacity:
		return true
	elif b.capacity > a.capacity:
		return false;
	else:
		return a.stack_size > b.stack_size;

func generate_storages()->void:
	for s:PackedScene in Index.resource_storage_scenes:
		var storage:ResourceContainer = s.instantiate();
		holder[storage.resource+"_storage"]=storage;
		add_item(storage, true);
		non_sellable_items.append(storage)
